export const HOUR_IN_MILLISECONDS = 3600 * 1000;
export const WEEK_IN_HOURS = 24 * 7;
export const TWO_WEEKS_IN_HOURS = 24 * 14;
export const MONTH_IN_HOURS = 24 * 30;
export const DAY_IN_MILLISECONDS = 24 * HOUR_IN_MILLISECONDS;
export const WEEK_IN_MILLISECONDS = WEEK_IN_HOURS * HOUR_IN_MILLISECONDS;
export const TWO_WEEKS_IN_MILLISECONDS =
  TWO_WEEKS_IN_HOURS * HOUR_IN_MILLISECONDS;
export const MONTH_IN_MILLISECONDS = MONTH_IN_HOURS * HOUR_IN_MILLISECONDS;
